### PR TITLE
Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by zhongyi-zhang**
Resubmit a PR to cover https://github.com/openservicebrokerapi/osb-checker/pull/2.

### CODE REVIEW

**Comment by mattmcneeney** [comment]
@zhongyi-zhang I've found the problem - @leonwanghui was not a collaborator of this repo. I've fixed this, so once @leonwanghui has accepted the invite, I'll get pullapprove to try again.

**Comment by leonwanghui** [comment]
Thanks @mattmcneeney 
Hi @zhongyi-zhang I have accepted the invitation, please reopen this PR to see if it works.

**Comment by zhongyi-zhang** [comment]
It seems reopening doesn't work. I'll try creating a new one.

**Comment by zhongyi-zhang** [comment]
The new PR https://github.com/openservicebrokerapi/osb-checker/pull/53 doesn't work, either...

**Comment by mattmcneeney** [comment]
@zhongyi-zhang I had to restart pullapprove again. All working now I think! cc @leonwanghui

**Pull request closed without merging**
