### PR TITLE
Removed config_azure.json

### PR DESCRIPTION
**Pull request by tinygrasshopper**

### CODE REVIEW

**Comment by mattmcneeney** [comment]
@Haishi2016 Any reason why we can't do this? We discussed on today's OSBAPI call that it seems weird having vendor specific config files as part of this repo.

**Comment by leonwanghui** [comment]
Hi @mattmcneeney , I think you were right about demonstrating how to replace mock config path with real vendors' config path. So if all vendor specific config files are removed, we should figure out how to provide an elegant way for user to configure their own config files, or they just need to pass a minimal config file (just like #34 ) rather than importing the whole config file.

**Comment by mattmcneeney** [comment]
@leonwanghui Absolutely - I think this repo needs some attention and could be made much easier to use. I don't think it would be wise to simply replicate the entire set of `v2.13` tests for `v2.14`, as changes are additive. If you have the time to take this on, that would be awesome! We started talking about this a while ago in #21

**Comment by leonwanghui** [comment]
I think this PR can be closed now : )

**Comment by norshtein** [comment]
The change is included in #50 . Close this PR.

**Comment by zhongyi-zhang** [comment]
It was already removed by https://github.com/openservicebrokerapi/osb-checker/pull/50. Actually the Azure Service Broker, a.k.a. OSBA, can't pass all the test cases of this checker. The reason is mainly in the checker side -- the test framework is not in enough good shape to test on a real service broker. @leonwanghui @mattmcneeney I agree with you that a config file to test on a real service broker is helpful. I'd like to make OSBA becoming a model which can pass all the test cases in OSB checker. Of course first of all, the test cases should definitely reflect OSB API spec. OSBA will also follow up on this if it can't pass any of the test cases. When we achieve the goal, the azure config file can be add back.

**Pull request closed without merging**
