### PR TITLE
Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by zhongyi-zhang**
Resubmit a PR to cover #2.

### CODE REVIEW

**Comment by mattmcneeney** [comment]
Pullapprove error is gone 😄

**Comment by norshtein** [comment]
Hi @mattmcneeney , seems @zhongyi-zhang is absent in the approver list...

**Comment by mattmcneeney** [comment]
@norshtein Fixing that now..

**Comment by mattmcneeney** [comment]
I think this is fixed! @zhongyi-zhang may not be showing in the apporvers list for this PR since they created it...

**Comment by norshtein** [comment]
Thanks @mattmcneeney for the effort!

**Comment by norshtein** [comment]
LGTM

**Comment by norshtein** [comment]
Reopen the PR to see whether CI effects. Sorry for disturb.

**Comment by zhongyi-zhang** [comment]
The number of required approvals is 2. So, @leonwanghui could you give an approval on this PR?

**Comment by mattmcneeney** [comment]
@leonwanghui This needs your +1 again - restarted it to check Travis CI was working (which it is!)

**Comment by zhongyi-zhang** [comment]
Thank you guys! Merged.

**Pull request merged**
