### PR TITLE
remove trailing whitespaces

### PR DESCRIPTION
**Pull request by jmrodri**

### CODE REVIEW

**Comment by avade** [comment]
lgtm

**Comment by mattmcneeney** [comment]
@jmrodri a few conflicts to resolve please!

**Comment by jmrodri** [comment]
@mattmcneeney sorry for the delay, fixed.

**Comment by mattmcneeney** [comment]
More conflicts @jmrodri :(

**Comment by zhongyi-zhang** [comment]
@jmrodri thanks for the contribution! Sorry to bother you solving conflicts. I've created another PR to cover it. Closed this one.

**Pull request closed without merging**
